#!/bin/tcsh

if( ! $?BMPINSTALL ) then
  setenv BMPINSTALL "/usr/local/uf$USER"
endif

setenv BMPINSTALL "$BMPINSTALL"

source $BMPINSTALL/.ufcshrc

set pid = `pgrep -f CirrigPlc.jar`
if ("$pid" == "") then
  java -Xms64m -Xmx512m -jar ${BMPINSTALL}/bin/CirrigPlc.jar $argv[1-]
else
  echo Sorry, ufcirrigPlc is already running with pid "$pid".  Use ufstop first.
endif

exit
