#!/bin/tcsh
unlimit
limit coredumpsize 0

source $BMPINSTALL/.ufcshrc
if ( ! -e $HOME/bmplogs) mkdir -p $HOME/bmplogs
set logdate = `date "+%Y-%m-%d.%H:%M"`

java -Xms64m -Xmx512m -Djdd.data_path=${BMPINSTALL}/wthjec/ -jar ${BMPINSTALL}/wthjec/wthjec.jar -log $HOME/bmplogs/log.wthjec.${logdate} $argv[1-] >& $HOME/bmplogs/log.wthjec.${logdate} & 

exit
