#!/bin/tcsh
# rcsId = $Name:  $ $Id: checkCcrop,v 1.8 2011/05/02 20:41:06 warner Exp $

#parse args
set options = "-sqluser mybmp"
set logdate = `date "+%Y-%m-%d.%H:%M"`

set pid = `pgrep -f ufWeather`
if ("$pid" == "") then
  echo  starting  ufWeather  $options
  $BMPINSTALL/bin/ufWeather $options -log $HOME/bmplogs/log.ufWeather.${logdate} >& $HOME/bmplogs/log.ufWeather.${logdate} &
  sleep 3
endif
