!=======================================================================
!	Driver program for Container Production Model 
!	J. Ritchie, G. Schoene, T. Yeager...et al
!
!	using "WB: Main program for modular water balance, developed by J. Ritchie
!	Cheryl Porter, J. W. Jones" as a starting point
!
!	4/27/05 coding started M. Bostick
!	5/9/05 delivered M. Bostick
!	4/6/06 new Ritchie/Million Plant subroutine debugged by MB
!    5/11/06 new waterbalance and plant code JR,MB,JM 
!    8/23/06 new nitrogen subroutine JR,JM,MB
!    11/28/06 new pruning and LAI-based spacing code JM
!    11/30/06 new finish code  JM
!    6/8/07 new multiple year code JM
!    6/11/07 reworked code to output multiple years in one file CW
!    11-21-07 added plant and irrigation input file JM
!    1-24-08 changed d_TT and TT to RDT and DT to reflect high temp effect JR
!    7-15-08 modified temp bias function for RDT JR
!    2-5-09 modified growth equations JR
!    1-26-10 modified irrigation capture functions JR, JM
!    4-26-10 phosphorus added JM
!    9-1-11 new CF function JM

!=======================================================================
      PROGRAM Driver
      IMPLICIT NONE			!every variable must be defined
      SAVE
	CHARACTER RUN*32,WFNAME*48,SPEC*48,APPL*8,SCHED*8,FINISH*8,
     &MOVE*8,RAINCUT*4,IFNAME*48,PFNAME*48,SFFNAME*48,TDF*8,SF*8,
     &PRUNE*8,IN_STATUS*8
      INTEGER INIT,RATE,INTEG,DAY,DOY,PLT_YR,PLT_DOY,END_YR,DATE,
     &PLT_DATE,YR,START_YR,IS_FIRST,HARVDAY,MOVE1,MOVE2,MOVE3,IRR1,IRR2,
     &IRR3,TD_TF,TD_DAY,REL_DAYS,REL_DAYS2,CRF_DAYS,
     &CRF_DAYS2,MAD,CHK_DAY1,CHK_DAY2,CHK_DAY3,PR1,PR2,PR3,
     &IRYR,IRDOY,IRSTAT,NEXTIR,NOPMAX,SFYR,SFDOY,SFSTAT,NEXTSF
	PARAMETER (INIT=1,RATE=2,INTEG=3)
	REAL SOLAR,TMAX,TMIN,RAIN,LAT,LONG,ALT,PRESS,IRRIG,TMEAN,BTMEAN,
     &ILA,SWLL,SWDUL,SW,SW_cm,PTA,AREA_RATIO,S_VOL,POT_TOPAREA,
     &PTA0,PTA1,PTA2,PTA3,DT,RDT,TW,d_TW,LA,d_LA,LAI,RW,d_RW,
     &TW_Nact,RW_Nact,NUPTAKE,TW_Nopt,RW_Nopt,NSUP_MAX1,NSUP_MAX2,
     &N_TOP,N_ROOT,NDEMAND,DRAIN_N,TRELN,N_PLT,NSUPPLY,D_IRR0,
     &D_IRR1,D_IRR2,D_IRR3,MAD_TF,CF_IRR,CF_RAIN,CF1,CF2,
     &SWA_cm3,DRAIN_CUM_cm3,ET_CUM_cm3,POT_DRAIN_cm3,
     &RUNOFF_cm3,SWDUL_cm3,POTDIAM,NOM,TOT_NOM,MOVE_LAI,
     &HARV_HT,SIZE,IRRIG_CUM_cm3,RUNOFF_CUM_cm3,SWLL_cm3,THRU_IRR_cm3,
     &POT_IRRIG_cm3,THRU_cm3,SW_cm3,A_SW_cm3,RAIN_CUM_cm3,IRRIG_cm3,
     &SWDUL_cm,SWLL_cm,DRAIN_cm,RUNOFF_cm,POT_IRRIG_cm,D_IRR,POT_ET_cm,
     &POT_RAIN_cm,POT_DRAIN_cm,AVG_PTA,RAIN_CUM_cm,IRRIG_CUM_cm,
     &ET_CUM_cm,DRAIN_CUM_cm,RUNOFF_CUM_cm,IRRIG_cm,ET_cm,Y_RAIN_cm,
     &RAIN_cm,WSUF,NSUF,VP,IRR_NCONC,POT_IRR_N,POT_IRR_N_CUM,
     &RTPF,CROPEC,RUE,CINT,LGC1,LGC2,LGC3,LGC4,LGC5,TC1,
     &FERT,PCT_N,PCT_CRN,FERT_N,CRF_N,SUB_N,NRELEASE,CUMNRELEASE,
     &PEAKDAYS,PEAKRATE,RELEASERATE,FINALDAYS,
     &DRAIN_NCONC,CUMDRAIN_N,R_OFF_NCONC,CRF_N_BAL,
     &CRF_TFAC,FERTDAYS,AVGTEMP,AVGFD,FERT2,PCT_N2,CUMNRELEASE2,
     &AVGFD2,CRF_N2_BAL,CRF_N2,FERT_N2,FERTDAYS2,
     &FINALDAYS2,PEAKDAYS2,PEAKRATE2,NRELEASE2,
     &PCT_CRN2,RELEASERATE2,AVGTEMP2,TD_UPFAC,NLOAD,NLOAD_CUM,RUNOFF_N,
     &THRU_N,CUMRUNOFF_N,KINPUT,DTMIN,DTOPTMIN,DTOPTMAX,DTMAX,
     &HT,WIDTH,FCDR,BRAD,DRF,TBIAS,TMAXB,DTSLOPEMIN,DTSLOPEMAX,
     &HTC1,HTC2,SZC1,SZC2,WDC1,WDC2,
     &RDTN1,RDTN2,RDTX1,RDTX2,PHOTOTEMP1,
     &PHOTOTEMP2,PHOTOTEMP3,TEMFACSO,PARB,SINLAT,COSLAT,ESCOR,OM,
     &THETA,SINDEC,COSDEC,SINF,COSF,HRANG,ETR,H2,AIRMASS,TARCD,CDR,
     &CONT,TW_Noptmax,TW_Noptmin,DT_Nmax,DT_Nmin,TW_Nmin,
     &NSUF_C1,NSUF_C2,NSUP_RF,NSUP_C1,NSUP_C2,
     &NSUF_TF,SF_START,SF_END,SF_INT,SF_TF,SF_NCONC,H2O_NCONC,
     &CHK_HT1,CHK_HT2,CHK_HT3,CHK_W1,CHK_W2,CHK_W3,PR_H1,PR_W1,PR_H2,
     &PR_W2,PR_H3,PR_W3,PRTWF1,PRLAF1,IHT,IWD,TPR1,TPR2,
     &TPR3,CUT,TP,DRPV,PVLF,TP_cm3,NUPTAKE_CUM,ITW_Nact,
     &IRW_Nact,DT_DELAY,PRTWF2,PRLAF2,SW_TF,
     &PCT_P,PCT_K,PCT_P2,PCT_K2,ITW_Pact,IRW_Pact,
     &ITW_Kact,IRW_Kact,PSUP_MAX1,PSUP_MAX2,PSUP_RF,PSUP_C1,PSUP_C2,
     &PSUF_C1,PSUF_C2,PSUF_TF,TW_Poptmax,TW_Poptmin,DT_Pmax,DT_Pmin,
     &TW_Pmin,RW_Popt,H2O_PCONC,SF_PCONC,SUB_P,DRAIN_P,PRELEASE,
     &CUMPRELEASE,PRELEASE2,CUMPRELEASE2,POT_IRR_P,POT_IRR_P_CUM,
     &PUPTAKE,IRR_PCONC,DRAIN_PCONC,CUMDRAIN_P,R_OFF_PCONC,RUNOFF_P,
     &CUMRUNOFF_P,THRU_P,P_TOP,P_ROOT,TW_Pact,RW_Pact,TW_Popt,
     &PDEMAND,PSUPPLY,PSUF,PUPTAKE_CUM,MAD_DIF,PLOAD_CUM,
     &CRF_P_BAL,CRF_P_BAL2,RAIN_EF,RW_Noptdif,RW_Poptdif,DTC1,VPLT,
     &CF_MAX,NOP
     
**********************************************************************
!	INITILIZATION
**********************************************************************
      IS_FIRST = 1
      NEXTIR=1
      NEXTSF=1
      WRITE(*,*)'Run'
      READ(*,*)RUN
            
      SPEC=trim(run)//'_P_spec.txt'
      
C---------Initialize from p_spec file---------
      OPEN(UNIT=6,FILE=SPEC, STATUS='UNKNOWN')
	READ(6,'(/)')
	READ(6,*)PLT_DOY,START_YR,END_YR,MOVE,MOVE1,MOVE2,MOVE3,
     &MOVE_LAI,NOM
	READ(6,'(//)')
      READ(6,*)ILA,IHT,IWD,IN_STATUS,ITW_Nact,IRW_Nact,ITW_Pact,
     &IRW_Pact
      READ(6,'(//)')
      READ(6,*)FINISH,HARVDAY,HARV_HT
      READ(6,'(//)')
      READ(6,*)CHK_DAY1,CHK_HT1,CHK_W1,CHK_DAY2,CHK_HT2,CHK_W2,
     &CHK_DAY3,CHK_HT3,CHK_W3
      READ(6,'(//)')
      READ(6,*)S_VOL,POTDIAM,PTA0,PTA1,PTA2,PTA3
	READ(6,'(//)')
      READ(6,*)SWLL,SWDUL,TP,PVLF
	READ(6,'(//)')
      READ(6,*)SCHED,RAINCUT,IRR1,IRR2,IRR3,MAD,MAD_DIF,H2O_NCONC,
     &H2O_PCONC,RAIN_EF
	READ(6,'(//)')
      READ(6,*)D_IRR0,D_IRR1,D_IRR2,D_IRR3
      READ(6,'(//)')
	READ(6,*)WFNAME,PFNAME,IFNAME,SFFNAME
      READ(6,'(//)')
	READ(6,*)FERT,PCT_CRN,PCT_N,PCT_P,PCT_K,CRF_DAYS,APPL
      READ(6,'(//)')
	READ(6,*)TDF,TD_DAY,TD_TF,FERT2,PCT_CRN2,PCT_N2,PCT_P2,PCT_K2,
     &CRF_DAYS2
      READ(6,'(//)')
	READ(6,*)SF,SF_START,SF_END,SF_INT,SF_TF,SF_NCONC,SF_PCONC
	READ(6,'(//)')
	READ(6,*)PRUNE,PR1,PR_H1,PR_W1,PR2,PR_H2,PR_W2,PR3,PR_H3,PR_W3,
     &TPR1,TPR2,TPR3,CUT,NOPMAX
      CLOSE(UNIT=6)
      
	YR=START_YR
	PLT_YR=START_YR
	
C-------Read plant file
      OPEN(UNIT=3,FILE=(Trim(PFNAME))//'.plt',STATUS='OLD')
      READ(3,'(/)')
      READ(3,*)CROPEC,CF1,KINPUT,DTMIN,DTOPTMIN,
     &DTOPTMAX,DTMAX,SW_TF
      READ(3,'(//)')
      READ(3,*)RTPF,LGC1,LGC2,LGC3,LGC4,LGC5,TC1,RUE,CINT,DTC1
      READ(3,'(//)')
      READ(3,*)NSUP_MAX1,NSUP_MAX2,NSUP_RF,NSUP_C1,NSUP_C2,NSUF_C1,
     &NSUF_C2,NSUF_TF
      READ(3,'(//)')
      READ(3,*)PSUP_MAX1,PSUP_MAX2,PSUP_RF,PSUP_C1,PSUP_C2,PSUF_C1,
     &PSUF_C2,PSUF_TF
      READ(3,'(//)')
      READ(3,*)TW_Noptmax,TW_Noptmin,DT_Nmax,DT_Nmin,TW_Nmin,RW_Noptdif
      READ(3,'(//)')
      READ(3,*)TW_Poptmax,TW_Poptmin,DT_Pmax,DT_Pmin,TW_Pmin,RW_Poptdif
      READ(3,'(//)')
      READ(3,*)HTC1,HTC2,WDC1,WDC2,SZC1,SZC2
      READ(3,'(//)')
      READ(3,*)PHOTOTEMP1,PHOTOTEMP2,PHOTOTEMP3
      READ(3,'(//)')
      READ(3,*)PRTWF1,PRTWF2,PRLAF1,PRLAF2
      CLOSE(UNIT=3)
        
C ------Read weather file headings---------
750   OPEN(UNIT=1,FILE=(Trim(WFNAME))//'.wth',STATUS='OLD')
	READ(1,'(//)')
700   READ(1,5)LAT,LONG,ALT

      LAT=LAT*0.01745      !CONVERTS DEGREES TO RADIANS
      SINLAT=SIN(LAT)
      COSLAT=COS(LAT)
      PRESS=(101.0-0.0107*ALT)/101.0		!Pressure (atm)
      
5     FORMAT(8X,2F9.3,F7.1)
      READ(1,'(/)')

C-------Read irrigation file heading---------
      IF(SCHED.eq.'FILE')THEN
       OPEN(UNIT=2,FILE=(Trim(IFNAME))//'.irr',STATUS='OLD')
       READ(2,'(/)')
      ENDIF
      IF(SCHED.eq.'REALTIME'.and.YR.eq.START_YR)THEN
       OPEN(UNIT=2,FILE=(Trim(IFNAME))//'.irr',STATUS='OLD')
       READ(2,'(/)')
      ENDIF
                      	      	
C ------Read fertigation file heading---------
      IF(SF.eq.'FILE')THEN
       OPEN(UNIT=4,FILE=(Trim(SFFNAME))//'.sfn',STATUS='OLD')
       READ(4,'(/)')
      ENDIF
          
C-------- Initialize    
      DTSLOPEMIN=1/(DTOPTMIN-DTMIN)
      DTSLOPEMAX=1/(DTMAX-DTOPTMAX)
      
      DT=(max(ILA-DTC1,0.)/LGC1)**(1/LGC2)
      DAY=0
      AVGTEMP=0
	AVGTEMP2=0
	
      POT_TOPAREA=3.14159*(POTDIAM/2)**2
      PTA=PTA0
      AVG_PTA=PTA0
      LAI=LA/PTA
	AREA_RATIO=PTA/POT_TOPAREA
	TOT_NOM=0

	CF2=CF1*-(POT_TOPAREA*7.39-716)+POT_TOPAREA 

	SW=SWDUL
      D_IRR=D_IRR0
	POT_IRR_N_CUM=0
		    
C*******************************************
	CALL WaterBalance(INIT,SOLAR,TMEAN,BTMEAN,RAIN_cm,
     &WFNAME,LA,DAY,YR,DOY,PRESS,RAINCUT,CF_IRR,CF_RAIN,MAD_TF,
     &POT_TOPAREA,WSUF,SCHED,PTA,AREA_RATIO,SWLL,SWDUL,SW,SW_cm,S_VOL,
     &CROPEC,MAD,IRRIG,D_IRR,IRRIG_CUM_cm3,RUNOFF_CUM_cm3,ET_CUM_cm3,
     &DRAIN_CUM_cm3,RAIN_CUM_cm3,RUNOFF_cm3,IRRIG_cm3,SWLL_cm3,
     &SWDUL_cm3,THRU_cm3,A_SW_cm3,SWA_cm3,SW_cm3,POT_DRAIN_cm3,
     &POT_IRRIG_cm3,THRU_IRR_cm3,SWLL_cm,DRAIN_cm,RUNOFF_cm,
     &POT_IRRIG_cm,POT_ET_cm,SWDUL_cm,POT_RAIN_cm,IRRIG_cm,ET_cm,TMIN,
     &TMAX,Y_RAIN_cm,POT_DRAIN_cm,DRAIN_CUM_cm,ET_CUM_cm,IRRIG_CUM_cm,
     &RAIN_CUM_cm,RUNOFF_CUM_cm,IRYR,IRDOY,IRSTAT,NEXTIR,TP,DRPV,TBIAS,
     &TP_cm3,LAI,SW_TF,MAD_DIF,CDR,RAIN_EF)
 	 
	Call Plant(INIT,DAY,DOY,SOLAR,TMAX,TMIN,DT,RDT,ILA,
     &LA,d_LA,LAI,RW,d_RW,TW,d_TW,SIZE,PTA,RTPF,
     &LGC1,LGC2,LGC3,LGC4,LGC5,RUE,CINT,DTC1,
     &SUB_N,NUPTAKE,NDEMAND,NSUPPLY,TRELN,N_TOP,N_ROOT,
     &N_PLT,TW_Nact,RW_Nact,TW_Nopt,RW_Nopt,TW_Nmin,SWDUL_cm3,
     &PRUNE,WSUF,NSUF,NSUP_MAX1,NSUP_MAX2,NSUP_C1,NSUP_C2,HT,WIDTH,HTC1,
     &HTC2,SZC1,SZC2,WDC1,WDC2,TBIAS,PHOTOTEMP1,
     &PHOTOTEMP2,PHOTOTEMP3,TEMFACSO,PARB,TW_Noptmax,TW_Noptmin,
     &DT_Nmax,DT_Nmin,NSUF_C1,NSUF_C2,NSUP_RF,NSUF_TF,S_VOL,
     &CHK_DAY1,CHK_DAY2,CHK_DAY3,CHK_HT1,CHK_W1,CHK_HT2,CHK_W2,CHK_HT3,
     &CHK_W3,POTDIAM,PR1,PR2,PR3,PR_H1,PR_W1,PR_H2,PR_W2,PR_H3,PR_W3,
     &PRTWF1,PRLAF1,IHT,IWD,TPR1,TPR2,TPR3,CUT,NOPMAX,PSUP_MAX1,
     &NUPTAKE_CUM,IN_STATUS,ITW_Nact,IRW_Nact,PRTWF2,PRLAF2,ITW_Pact,
     &IRW_Pact,ITW_Kact,IRW_Kact,PSUP_MAX2,PSUP_RF,PSUP_C1,PSUP_C2,
     &PSUF_C1,PSUF_C2,PSUF_TF,TW_Poptmax,TW_Poptmin,DT_Pmax,DT_Pmin,
     &TW_Pmin,RW_Popt,SUB_P,P_TOP,P_ROOT,TW_Pact,RW_Pact,TW_Popt,
     &PDEMAND,PUPTAKE,PSUPPLY,PSUF,PUPTAKE_CUM,RW_Noptdif,RW_Poptdif,
     &NOP)
     
      Call Nutrient(INIT,CRF_N,CRF_DAYS,NRELEASE,CUMNRELEASE,
     &RELEASERATE,FERT_N,SUB_N,FERT,PCT_N,PCT_CRN,SWDUL_cm3,NUPTAKE,
     &DRAIN_N,DRAIN_NCONC,CUMDRAIN_N,POT_DRAIN_cm3,REL_DAYS,PEAKDAYS,
     &FINALDAYS,PEAKRATE,R_OFF_NCONC,RUNOFF_cm3,
     &CRF_N_BAL,TMEAN,VP,CRF_TFAC,FERTDAYS,AVGFD,FERT2,CRF_N2,
     &CRF_DAYS2,NRELEASE2,CUMNRELEASE2,RELEASERATE2,FERT_N2,PCT_N2,
     &PCT_CRN2,PEAKDAYS2,FINALDAYS2,PEAKRATE2,
     &CRF_N2_BAL,FERTDAYS2,AVGFD2,TD_DAY,REL_DAYS2,TD_TF,NDEMAND,
     &DAY,YR,DOY,NLOAD,NLOAD_CUM,PTA,THRU_IRR_cm3,IRR_NCONC,
     &RUNOFF_N,THRU_N,CUMRUNOFF_N,H2O_NCONC,SF,SF_START,SF_END,SF_INT,
     &SF_NCONC,TDF,SF_TF,DRPV,PVLF,TBIAS,SWLL_cm3,TP_cm3,SFYR,SFDOY,
     &SFSTAT,NEXTSF,PCT_P,PCT_K,PCT_P2,PCT_K2,H2O_PCONC,SF_PCONC,SUB_P,
     &DRAIN_P,PRELEASE,CUMPRELEASE,PRELEASE2,CUMPRELEASE2,
     &DRAIN_PCONC,CUMDRAIN_P,R_OFF_PCONC,RUNOFF_P,CRF_P_BAL,CRF_P_BAL2,
     &CUMRUNOFF_P,THRU_P,POT_IRR_P,POT_IRR_P_CUM,PLOAD_CUM)
	 
	Call Output(INIT,LA,LAI,SW_cm,POT_ET_cm,POT_RAIN_cm,
     &POT_IRRIG_cm,DRAIN_cm,RUNOFF_cm,CF_IRR,TW,RW,DT,SOLAR,TMIN,TMAX,
     &RAIN_cm,IRRIG_cm, N_TOP,N_ROOT,TW_Nact,RW_Nact,NDEMAND,NUPTAKE,
     &NSUPPLY,NRELEASE,d_TW,d_RW,TW_Nopt,RW_Nopt,NSUF,SUB_N,
     &DRAIN_NCONC,DRAIN_N,CUMDRAIN_N,HARVDAY,RAIN_CUM_cm3,IRRIG_CUM_cm3,
     &ET_CUM_cm3,DRAIN_CUM_cm3,RUNOFF_CUM_cm3,RUN,
     &R_OFF_NCONC,RUNOFF_cm3,CRF_DAYS,CRF_N,PEAKDAYS,
     &AVGTEMP2,PEAKRATE,FINALDAYS,RELEASERATE,CUMNRELEASE,CRF_N_BAL,
     &VP,AVGFD2,CRF_TFAC,FERTDAYS,TMEAN,AVGTEMP,AVGFD,SIZE,NRELEASE2,
     &CRF_N2_BAL,REL_DAYS2,HARV_HT,POT_IRR_N,POT_IRR_N_CUM,
     &YR,PLT_YR,DOY,WSUF,FINISH,IS_FIRST,POT_DRAIN_cm,PTA,AVG_PTA,
     &POT_DRAIN_cm3,RAIN_CUM_cm,IRRIG_CUM_cm,ET_CUM_cm,DRAIN_CUM_cm,
     &RUNOFF_CUM_cm,NLOAD,NLOAD_CUM,ET_cm,DAY,THRU_N,
     &RUNOFF_N,CUMRUNOFF_N,HT,WIDTH,TMAXB,FCDR,DRF,RDT,TEMFACSO,IRSTAT,
     &NUPTAKE_CUM,TBIAS,P_TOP,P_ROOT,TW_Pact,RW_Pact,
     &TW_Popt,RW_Popt,PDEMAND,PUPTAKE,PSUPPLY,PSUF,PUPTAKE_CUM,
     &SUB_P,DRAIN_PCONC,DRAIN_P,PRELEASE,CUMDRAIN_P,R_OFF_PCONC,
     &RUNOFF_P,CUMRUNOFF_P,THRU_P,POT_IRR_P,POT_IRR_P_CUM,PLOAD_CUM,
     &CUMPRELEASE,CRF_P_BAL,CRF_P_BAL2,PRELEASE2,TOT_NOM,NOP)
     
      
!**********************************************************************
!	END INITILIZATION
!**********************************************************************
!     Begin Daily Simulation
!***********************************************************************
     
C-----Read YR,DOY,SOLAR,TMAX,TMIN,RAIN for the day
      
       DO WHILE(YR.GT.0)
	   
800      READ(1,20,END=900)YR,DOY,SOLAR,TMAX,TMIN,RAIN
           
!           if(RAIN<100)then   !to test rain effect
!           rain=0.
!           endif      

C----- Calculations for daylength and PARB     
         ESCOR=1-0.016733*COS(0.0172*(DOY-1))  !EARTH SUN DISTANCE CORRECTION
         OM=0.017202*(DOY-3.244)
         THETA=OM+0.03344*SIN(OM)*(1-0.15*SIN(OM))-1.3526
         SINDEC=0.3978*SIN(THETA)
         COSDEC=(1-SINDEC**2)**0.5
         SINF=SINDEC*SINLAT
         COSF=COSDEC*COSLAT
         HRANG=ACOS(-SINF/COSF)       !HOUR ANGLE OF SUN - RADIANS
         ETR=37.21/ESCOR**2*(HRANG*SINF+COSF*SIN(HRANG)) !^EXTRATERRESTIAL SOLAR RADIATION-MJ/m**2/RAD
         H2=SINF+COSF*COS(HRANG/2.) !emprical coeff for optical airmass calcs
         AIRMASS=PRESS*(-16.886*H2**3+36.137*H2**2-27.462*H2+8.7412)  !optical airmass
         TARCD=0.87-0.0025*TMIN   !clear day transmissivity or air
         CDR=ETR*TARCD**AIRMASS
         FCDR=min(SOLAR/CDR,1.)
         DRF=max(1.33*(FCDR-0.25),0.0)   !direct radiation fraction              
         PARB=min(SOLAR*0.5,CDR*0.5*TC1) !jr 3-12-09 changed from using daylength to clear day radiation
         
C----- Calculations for bias temp             
         BRAD=SOLAR*DRF*exp(-0.7*LAI)*(1-POT_TOPAREA/PTA)  !jr 2-13-08 
         TMAXB=TMAX+KINPUT*BRAD
         TMEAN=max((TMAX*0.5+TMIN*0.5),0.1)  !true mean
         TBIAS=(TMIN+TMAXB)/2   !bias temp for TEMFACSO for photosynthesis
         BTMEAN=TMAXB*0.75+TMIN*0.25   !bias mean for vpd for evaporation
         
C----- Calculations for relative development time           
         RDTN1=min(DTSLOPEMIN*(TMAXB-DTMIN),1.)
         RDTN2=min(DTSLOPEMIN*(TMIN-DTMIN),1.)
         RDTX1=min(-DTSLOPEMAX*(TMAXB-DTMAX),1.)
         RDTX2=min(-DTSLOPEMAX*(TMIN-DTMAX),1.)
         RDT=max(min((RDTN1+RDTN2)*0.5,(RDTX1+RDTX2)*0.5),0.01)
          
20    FORMAT(I4,I3,5F6.1)
                   
      DATE=YR*1000+DOY                  !used to control finish of each season
      PLT_DATE=PLT_YR*1000+PLT_DOY      !used to control finish of each season
      
	RAIN_cm=RAIN/10   !convert mm to cm
	
	CONT=0
		
	IF(FINISH.eq.'FIXED'.and.YR.ge.PLT_YR.and.DATE.ge.PLT_DATE
     &.and.DAY.lt.HARVDAY) THEN
         CONT=1
	ELSEIF(FINISH.eq.'SIZE'.and.YR.ge.PLT_YR.and.DATE.ge.PLT_DATE
     &.and.HT.lt.HARV_HT.AND.NSUF.gt.0.05) THEN
         CONT=1
      ENDIF
       
      !IF(NSUF.gt.0.05)THEN
      !   CONT=1
      !ENDIF

      IF(CONT.eq.1) THEN
        DAY=DAY+1
        DT=DT+RDT
	 
	  AVGTEMP=(AVGTEMP*(DAY-1)+TBIAS)/DAY  !running average
	
	IF(SCHED.eq.'FILE'.and.NEXTIR.eq.1)THEN 
        NEXTIR=0
        READ(2,22,IOSTAT=IRSTAT)IRYR,IRDOY,IRRIG
22      FORMAT(I4,I3,F5.2) 
      ELSEIF (SCHED.eq.'REALTIME'.and.NEXTIR.eq.1) THEN
        NEXTIR=0
        READ(2,23,IOSTAT=IRSTAT)IRYR,IRDOY,IRRIG
23      FORMAT(I4,I3,F5.2)
      ENDIF
     
      IF(SF.eq.'FILE'.and.NEXTSF.eq.1)THEN 
        NEXTSF=0
        READ(4,42,IOSTAT=SFSTAT)SFYR,SFDOY,SF_NCONC,SF_PCONC
42      FORMAT(I4,I3,F6.0,F4.0)  
      ENDIF
        
C--------recalculate areas after moving pots---------
	IF(MOVE.eq.'FIXED') THEN
        IF(DAY.eq.MOVE1) THEN
	      PTA=PTA1
	      LAI=LA/PTA
	      AREA_RATIO=PTA/POT_TOPAREA
	  ELSEIF(DAY.eq.MOVE2) THEN
	      PTA=PTA2
	      LAI=LA/PTA
	      AREA_RATIO=PTA/POT_TOPAREA
	  ELSEIF(DAY.eq.MOVE3) THEN
	      PTA=PTA3
	      LAI=LA/PTA
	      AREA_RATIO=PTA/POT_TOPAREA
	  ENDIF
	ELSEIF(MOVE.eq.'LAI')THEN
        IF(LAI.ge.MOVE_LAI.and.TOT_NOM.lt.NOM) THEN
	      PTA=PTA1
	      LAI=LA/PTA
	      AREA_RATIO=PTA/POT_TOPAREA
	      TOT_NOM=TOT_NOM+1
	  ENDIF
	ENDIF
      
	AVG_PTA=(AVG_PTA*(DAY-1)+PTA)/DAY  !running average
	
C-------reset irrigation rates-------
      IF(DAY.eq.IRR1) THEN
        D_IRR=D_IRR1
      ELSEIF(DAY.eq.IRR2) THEN
        D_IRR=D_IRR2
      ELSEIF(DAY.eq.IRR3) THEN
        D_IRR=D_IRR3
      ENDIF
      
!***********************************************************************
C     RATE calculations       
!***********************************************************************
      CALL WaterBalance(RATE,SOLAR,TMEAN,BTMEAN,RAIN_cm,
     &WFNAME,LA,DAY,YR,DOY,PRESS,RAINCUT,CF_IRR,CF_RAIN,MAD_TF,
     &POT_TOPAREA,WSUF,SCHED,PTA,AREA_RATIO,SWLL,SWDUL,SW,SW_cm,S_VOL,
     &CROPEC,MAD,IRRIG,D_IRR,IRRIG_CUM_cm3,RUNOFF_CUM_cm3,ET_CUM_cm3,
     &DRAIN_CUM_cm3,RAIN_CUM_cm3,RUNOFF_cm3,IRRIG_cm3,SWLL_cm3,
     &SWDUL_cm3,THRU_cm3,A_SW_cm3,SWA_cm3,SW_cm3,POT_DRAIN_cm3,
     &POT_IRRIG_cm3,THRU_IRR_cm3,SWLL_cm,DRAIN_cm,RUNOFF_cm,
     &POT_IRRIG_cm,POT_ET_cm,SWDUL_cm,POT_RAIN_cm,IRRIG_cm,ET_cm,TMIN,
     &TMAX,Y_RAIN_cm,POT_DRAIN_cm,DRAIN_CUM_cm,ET_CUM_cm,IRRIG_CUM_cm,
     &RAIN_CUM_cm,RUNOFF_CUM_cm,IRYR,IRDOY,IRSTAT,NEXTIR,TP,DRPV,TBIAS,
     &TP_cm3,LAI,SW_TF,MAD_DIF,CDR,RAIN_EF)
 	 
	Call Plant(RATE,DAY,DOY,SOLAR,TMAX,TMIN,DT,RDT,ILA,
     &LA,d_LA,LAI,RW,d_RW,TW,d_TW,SIZE,PTA,RTPF,
     &LGC1,LGC2,LGC3,LGC4,LGC5,RUE,CINT,DTC1,
     &SUB_N,NUPTAKE,NDEMAND,NSUPPLY,TRELN,N_TOP,N_ROOT,
     &N_PLT,TW_Nact,RW_Nact,TW_Nopt,RW_Nopt,TW_Nmin,SWDUL_cm3,
     &PRUNE,WSUF,NSUF,NSUP_MAX1,NSUP_MAX2,NSUP_C1,NSUP_C2,HT,WIDTH,HTC1,
     &HTC2,SZC1,SZC2,WDC1,WDC2,TBIAS,PHOTOTEMP1,
     &PHOTOTEMP2,PHOTOTEMP3,TEMFACSO,PARB,TW_Noptmax,TW_Noptmin,
     &DT_Nmax,DT_Nmin,NSUF_C1,NSUF_C2,NSUP_RF,NSUF_TF,S_VOL,
     &CHK_DAY1,CHK_DAY2,CHK_DAY3,CHK_HT1,CHK_W1,CHK_HT2,CHK_W2,CHK_HT3,
     &CHK_W3,POTDIAM,PR1,PR2,PR3,PR_H1,PR_W1,PR_H2,PR_W2,PR_H3,PR_W3,
     &PRTWF1,PRLAF1,IHT,IWD,TPR1,TPR2,TPR3,CUT,NOPMAX,PSUP_MAX1,
     &NUPTAKE_CUM,IN_STATUS,ITW_Nact,IRW_Nact,PRTWF2,PRLAF2,ITW_Pact,
     &IRW_Pact,ITW_Kact,IRW_Kact,PSUP_MAX2,PSUP_RF,PSUP_C1,PSUP_C2,
     &PSUF_C1,PSUF_C2,PSUF_TF,TW_Poptmax,TW_Poptmin,DT_Pmax,DT_Pmin,
     &TW_Pmin,RW_Popt,SUB_P,P_TOP,P_ROOT,TW_Pact,RW_Pact,TW_Popt,
     &PDEMAND,PUPTAKE,PSUPPLY,PSUF,PUPTAKE_CUM,RW_Noptdif,RW_Poptdif,
     &NOP)
      
      Call Nutrient(RATE,CRF_N,CRF_DAYS,NRELEASE,CUMNRELEASE,
     &RELEASERATE,FERT_N,SUB_N,FERT,PCT_N,PCT_CRN,SWDUL_cm3,NUPTAKE,
     &DRAIN_N,DRAIN_NCONC,CUMDRAIN_N,POT_DRAIN_cm3,REL_DAYS,PEAKDAYS,
     &FINALDAYS,PEAKRATE,R_OFF_NCONC,RUNOFF_cm3,
     &CRF_N_BAL,TMEAN,VP,CRF_TFAC,FERTDAYS,AVGFD,FERT2,CRF_N2,
     &CRF_DAYS2,NRELEASE2,CUMNRELEASE2,RELEASERATE2,FERT_N2,PCT_N2,
     &PCT_CRN2,PEAKDAYS2,FINALDAYS2,PEAKRATE2,
     &CRF_N2_BAL,FERTDAYS2,AVGFD2,TD_DAY,REL_DAYS2,TD_TF,NDEMAND,
     &DAY,YR,DOY,NLOAD,NLOAD_CUM,PTA,THRU_IRR_cm3,IRR_NCONC,
     &RUNOFF_N,THRU_N,CUMRUNOFF_N,H2O_NCONC,SF,SF_START,SF_END,SF_INT,
     &SF_NCONC,TDF,SF_TF,DRPV,PVLF,TBIAS,SWLL_cm3,TP_cm3,SFYR,SFDOY,
     &SFSTAT,NEXTSF,PCT_P,PCT_K,PCT_P2,PCT_K2,H2O_PCONC,SF_PCONC,SUB_P,
     &DRAIN_P,PRELEASE,CUMPRELEASE,PRELEASE2,CUMPRELEASE2,
     &DRAIN_PCONC,CUMDRAIN_P,R_OFF_PCONC,RUNOFF_P,CRF_P_BAL,CRF_P_BAL2,
     &CUMRUNOFF_P,THRU_P,POT_IRR_P,POT_IRR_P_CUM,PLOAD_CUM)
	   
!***********************************************************************
!     INTEGRATION calculations       
!***********************************************************************

C-------IRRIG and RAIN capture factors  JM 9-1-11
      VPLT=4/3*3.14159*(SIZE/2)**3
      CF_MAX=max(1.,(CF1*VPLT+CF2)/POT_TOPAREA)
      CF_IRR=min(CF_MAX,0.9*AREA_RATIO+0.1)
      
	CF_RAIN=CF_IRR    !needs to be investigated

      CALL WaterBalance(INTEG,SOLAR,TMEAN,BTMEAN,RAIN_cm,
     &WFNAME,LA,DAY,YR,DOY,PRESS,RAINCUT,CF_IRR,CF_RAIN,MAD_TF,
     &POT_TOPAREA,WSUF,SCHED,PTA,AREA_RATIO,SWLL,SWDUL,SW,SW_cm,S_VOL,
     &CROPEC,MAD,IRRIG,D_IRR,IRRIG_CUM_cm3,RUNOFF_CUM_cm3,ET_CUM_cm3,
     &DRAIN_CUM_cm3,RAIN_CUM_cm3,RUNOFF_cm3,IRRIG_cm3,SWLL_cm3,
     &SWDUL_cm3,THRU_cm3,A_SW_cm3,SWA_cm3,SW_cm3,POT_DRAIN_cm3,
     &POT_IRRIG_cm3,THRU_IRR_cm3,SWLL_cm,DRAIN_cm,RUNOFF_cm,
     &POT_IRRIG_cm,POT_ET_cm,SWDUL_cm,POT_RAIN_cm,IRRIG_cm,ET_cm,TMIN,
     &TMAX,Y_RAIN_cm,POT_DRAIN_cm,DRAIN_CUM_cm,ET_CUM_cm,IRRIG_CUM_cm,
     &RAIN_CUM_cm,RUNOFF_CUM_cm,IRYR,IRDOY,IRSTAT,NEXTIR,TP,DRPV,TBIAS,
     &TP_cm3,LAI,SW_TF,MAD_DIF,CDR,RAIN_EF)
 	   
	Call Plant(INTEG,DAY,DOY,SOLAR,TMAX,TMIN,DT,RDT,ILA,
     &LA,d_LA,LAI,RW,d_RW,TW,d_TW,SIZE,PTA,RTPF,
     &LGC1,LGC2,LGC3,LGC4,LGC5,RUE,CINT,DTC1,
     &SUB_N,NUPTAKE,NDEMAND,NSUPPLY,TRELN,N_TOP,N_ROOT,
     &N_PLT,TW_Nact,RW_Nact,TW_Nopt,RW_Nopt,TW_Nmin,SWDUL_cm3,
     &PRUNE,WSUF,NSUF,NSUP_MAX1,NSUP_MAX2,NSUP_C1,NSUP_C2,HT,WIDTH,HTC1,
     &HTC2,SZC1,SZC2,WDC1,WDC2,TBIAS,PHOTOTEMP1,
     &PHOTOTEMP2,PHOTOTEMP3,TEMFACSO,PARB,TW_Noptmax,TW_Noptmin,
     &DT_Nmax,DT_Nmin,NSUF_C1,NSUF_C2,NSUP_RF,NSUF_TF,S_VOL,
     &CHK_DAY1,CHK_DAY2,CHK_DAY3,CHK_HT1,CHK_W1,CHK_HT2,CHK_W2,CHK_HT3,
     &CHK_W3,POTDIAM,PR1,PR2,PR3,PR_H1,PR_W1,PR_H2,PR_W2,PR_H3,PR_W3,
     &PRTWF1,PRLAF1,IHT,IWD,TPR1,TPR2,TPR3,CUT,NOPMAX,PSUP_MAX1,
     &NUPTAKE_CUM,IN_STATUS,ITW_Nact,IRW_Nact,PRTWF2,PRLAF2,ITW_Pact,
     &IRW_Pact,ITW_Kact,IRW_Kact,PSUP_MAX2,PSUP_RF,PSUP_C1,PSUP_C2,
     &PSUF_C1,PSUF_C2,PSUF_TF,TW_Poptmax,TW_Poptmin,DT_Pmax,DT_Pmin,
     &TW_Pmin,RW_Popt,SUB_P,P_TOP,P_ROOT,TW_Pact,RW_Pact,TW_Popt,
     &PDEMAND,PUPTAKE,PSUPPLY,PSUF,PUPTAKE_CUM,RW_Noptdif,RW_Poptdif,
     &NOP)
      
      Call Nutrient(INTEG,CRF_N,CRF_DAYS,NRELEASE,CUMNRELEASE,
     &RELEASERATE,FERT_N,SUB_N,FERT,PCT_N,PCT_CRN,SWDUL_cm3,NUPTAKE,
     &DRAIN_N,DRAIN_NCONC,CUMDRAIN_N,POT_DRAIN_cm3,REL_DAYS,PEAKDAYS,
     &FINALDAYS,PEAKRATE,R_OFF_NCONC,RUNOFF_cm3,
     &CRF_N_BAL,TMEAN,VP,CRF_TFAC,FERTDAYS,AVGFD,FERT2,CRF_N2,
     &CRF_DAYS2,NRELEASE2,CUMNRELEASE2,RELEASERATE2,FERT_N2,PCT_N2,
     &PCT_CRN2,PEAKDAYS2,FINALDAYS2,PEAKRATE2,
     &CRF_N2_BAL,FERTDAYS2,AVGFD2,TD_DAY,REL_DAYS2,TD_TF,NDEMAND,
     &DAY,YR,DOY,NLOAD,NLOAD_CUM,PTA,THRU_IRR_cm3,IRR_NCONC,
     &RUNOFF_N,THRU_N,CUMRUNOFF_N,H2O_NCONC,SF,SF_START,SF_END,SF_INT,
     &SF_NCONC,TDF,SF_TF,DRPV,PVLF,TBIAS,SWLL_cm3,TP_cm3,SFYR,SFDOY,
     &SFSTAT,NEXTSF,PCT_P,PCT_K,PCT_P2,PCT_K2,H2O_PCONC,SF_PCONC,SUB_P,
     &DRAIN_P,PRELEASE,CUMPRELEASE,PRELEASE2,CUMPRELEASE2,
     &DRAIN_PCONC,CUMDRAIN_P,R_OFF_PCONC,RUNOFF_P,CRF_P_BAL,CRF_P_BAL2,
     &CUMRUNOFF_P,THRU_P,POT_IRR_P,POT_IRR_P_CUM,PLOAD_CUM)

      POT_IRR_N=IRR_NCONC*POT_IRRIG_cm3*0.000001    !N from irrigation water
      POT_IRR_N_CUM=POT_IRR_N_CUM+POT_IRR_N         !computes cumulative N from irrigation water
      
      POT_IRR_P=IRR_PCONC*POT_IRRIG_cm3*0.000001    !P from irrigation water
      POT_IRR_P_CUM=POT_IRR_P_CUM+POT_IRR_P         !computes cumulative P from irrigation water
     
     
      SUB_N=SUB_N-DRAIN_N+NRELEASE+NRELEASE2-NUPTAKE+POT_IRR_N   !daily N budget
      SUB_P=SUB_P-DRAIN_P+PRELEASE+PRELEASE2-PUPTAKE+POT_IRR_P   !daily P budget
      
      IF(REL_DAYS2.gt.0) THEN
	  AVGTEMP2=(AVGTEMP2*(REL_DAYS2-1)+TBIAS)/REL_DAYS2  !computes avg. during sidedress app
	ENDIF
	
     	Call Output(INTEG,LA,LAI,SW_cm,POT_ET_cm,POT_RAIN_cm,
     &POT_IRRIG_cm,DRAIN_cm,RUNOFF_cm,CF_IRR,TW,RW,DT,SOLAR,TMIN,TMAX,
     &RAIN_cm,IRRIG_cm, N_TOP,N_ROOT,TW_Nact,RW_Nact,NDEMAND,NUPTAKE,
     &NSUPPLY,NRELEASE,d_TW,d_RW,TW_Nopt,RW_Nopt,NSUF,SUB_N,
     &DRAIN_NCONC,DRAIN_N,CUMDRAIN_N,HARVDAY,RAIN_CUM_cm3,IRRIG_CUM_cm3,
     &ET_CUM_cm3,DRAIN_CUM_cm3,RUNOFF_CUM_cm3,RUN,
     &R_OFF_NCONC,RUNOFF_cm3,CRF_DAYS,CRF_N,PEAKDAYS,
     &AVGTEMP2,PEAKRATE,FINALDAYS,RELEASERATE,CUMNRELEASE,CRF_N_BAL,
     &VP,AVGFD2,CRF_TFAC,FERTDAYS,TMEAN,AVGTEMP,AVGFD,SIZE,NRELEASE2,
     &CRF_N2_BAL,REL_DAYS2,HARV_HT,POT_IRR_N,POT_IRR_N_CUM,
     &YR,PLT_YR,DOY,WSUF,FINISH,IS_FIRST,POT_DRAIN_cm,PTA,AVG_PTA,
     &POT_DRAIN_cm3,RAIN_CUM_cm,IRRIG_CUM_cm,ET_CUM_cm,DRAIN_CUM_cm,
     &RUNOFF_CUM_cm,NLOAD,NLOAD_CUM,ET_cm,DAY,THRU_N,
     &RUNOFF_N,CUMRUNOFF_N,HT,WIDTH,TMAXB,FCDR,DRF,RDT,TEMFACSO,IRSTAT,
     &NUPTAKE_CUM,TBIAS,P_TOP,P_ROOT,TW_Pact,RW_Pact,
     &TW_Popt,RW_Popt,PDEMAND,PUPTAKE,PSUPPLY,PSUF,PUPTAKE_CUM,
     &SUB_P,DRAIN_PCONC,DRAIN_P,PRELEASE,CUMDRAIN_P,R_OFF_PCONC,
     &RUNOFF_P,CUMRUNOFF_P,THRU_P,POT_IRR_P,POT_IRR_P_CUM,PLOAD_CUM,
     &CUMPRELEASE,CRF_P_BAL,CRF_P_BAL2,PRELEASE2,TOT_NOM,NOP)
      
      ENDIF         
                 
      ENDDO			! End of daily loop
      
900   CONTINUE
890   PLT_YR=PLT_YR+1
      CLOSE(UNIT=1)
      IS_FIRST = 0
      IF(PLT_YR.le.END_YR) THEN
         GO TO 750         
      ENDIF
      CLOSE(UNIT=2)
      CLOSE(UNIT=4)
      
      END PROGRAM DRIVER
