#!/bin/tcsh

if( ! $?BMPINSTALL ) then
  setenv BMPINSTALL "/usr/local/uf$USER"
endif

setenv BMPINSTALL "$BMPINSTALL"

source $BMPINSTALL/.ufcshrc

set pid = `pgrep -f Weather.jar`
if ("$pid" == "") then
  java -jar ${BMPINSTALL}/bin/Weather.jar $argv[1-]
else
  echo Sorry, ufWeather is already running with pid "$pid".  Use ufstop first.
endif

exit
